name: CI

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'LICENSE'
      - '**.md'
  pull_request:
    paths-ignore:
      - 'LICENSE'
      - '**.md'

env:
  BUILD_TYPE: Release
  BUILD_DIR: ${{github.workspace}}/build

jobs:
  basic_build:
    name: basic_build (${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: windows-latest
            cores_cmd: echo $env:NUMBER_OF_PROCESSORS
          - os: macos-latest
            cores_cmd: sysctl -n hw.logicalcpu
          - os: ubuntu-latest
            cores_cmd: nproc

    steps:
      - uses: actions/checkout@v7.0.1
        with:
          submodules: recursive

      - name: Configure
        run: cmake -B "${{env.BUILD_DIR}}" -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

      - name: Build
        run: cmake --build "${{env.BUILD_DIR}}" --config ${{env.BUILD_TYPE}} --parallel $(${{ matrix.cores_cmd }})

  ladder_build:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v7.0.1
        with:
          submodules: recursive

      - name: Configure
        run: cmake -B "${{env.BUILD_DIR}}" -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DBUILD_FOR_LADDER=ON -DSC2_VERSION=4.10.0

      - name: Build
        run: cmake --build "${{env.BUILD_DIR}}" --config ${{env.BUILD_TYPE}} --parallel $(nproc)
